version: '3.8'

services:
  app:
    container_name: ${PROJECT_NAME}.app
    build: configs/symfony
    restart: unless-stopped
    volumes:
      - ./app:/var/www/app

  db:
    container_name: ${PROJECT_NAME}.db
    image: mysql:8.0.35
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123qwerty
      - MYSQL_DATABASE=app
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    container_name: ${PROJECT_NAME}.nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./configs/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./configs/nginx/startup-script.sh:/startup-script.sh
      - ./app:/var/www/app
    command: ["/startup-script.sh"]
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
    depends_on:
      - app
      - db

  phpmyadmin:
    container_name: ${PROJECT_NAME}.phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=123qwerty
    depends_on:
      - db

#  redis:
#    container_name: ${PROJECT_NAME}.redis
#    image: redis:latest
#    restart: unless-stopped
#    volumes:
#      - redis_data:/data

#  memcached:
#    container_name: ${PROJECT_NAME}.memcached
#    image: memcached:latest
#    restart: unless-stopped
#    command: memcached -m 64

volumes:
  db_data:
  redis_data:

networks:
  default:
    name: ${PROJECT_NAME}